# Main configuration file for tissueMAP.
# 
# NOTE: you may use environment variables in this file, e.g. ${oc.env:TISSUEMAP_RESOURCES_DIR}.
# The TISSUEMAP_RESOURCES_DIR environment variable is a special environment variable that, if not set, will be set to the resources/ directory relative to where tissueMAP is installed.

# Only use absolute paths!


training: # used when training the tissue patch classifier
  output_dir:
  train_dir:
  valid_dir:
  backbone: google/efficientnet-b0
  # backbones:
  #   ctp
  #   uni
  #   google/efficientnet-b0
  #   google/efficientnet-b3
  #   microsoft/swinv2-tiny-patch4-window8-256
  binary: false
  batch_size: 32
  ignore_categories: [DEB]
  cores: 8

preprocessing:
  output_dir:
  wsi_dir: 
  classifier_path:
  cache_dir:
  feat_extractor: ctp 
  microns: 256
  norm: false
  normalization_template: ${oc.env:TISSUEMAP_RESOURCES_DIR}/normalization_template.jpg 
  del_slide: false 
  cache: true
  only_feature_extraction: false 
  cores: 8 
  device: cuda:0 
  batch_size: 64

visualizing:
  clini_table: # Path to clini_table file (.xlsx or .csv)
  slide_table: # Path to slide_table file (.xlsx or .csv)
  feature_dir: ${preprocessing.output_dir}/tissueMAP_macenko_xiyuewang-ctranspath-7c998680 # Path to feature directory
  output_dir: # Path to output directory
  target_label: # Target label. No spaces allowed! Format clinical table accordingly
  categories: [] # Categories (list), leave empty to automatically infer based on unique values in the target_label column
  cat_labels: [] # Extra input category labels (list, can be empty)
  cont_labels: [] # Extra input continuous labels (list, can be empty)
  n_splits: 5 # Number of splits for cross-validation (only applicable to cross-validation)
  model_path: /path/to/export.pkl # Path to saved model (only applicable to deployment)
  deploy_feature_dir: # Path to directory containing the external cohort features (only applicable to deployment)
  